### ISSUE TITLE
 Unexpected key(s) in state_dict: "up1.model.0.weight", 

### ISSUE THREAD

**Issue by msk7131** [lime-j/DeepFSPIS#2]
Unexpected key(s) in state_dict: "up1.model.0.weight", "up1.model.0.bias", "up1.model.1.pa0.weight", "up1.model.1.pa0.bias", "up1.model.1.pa1.0.weight", "up1.model.1.pa1.0.bias", "up1.model.2.ca0.weight", "up1.model.2.ca0.bias", "up1.model.2.ca1.weight", "up1.model.2.ca1.bias", "up1.relu.weight"

how to deal with this

**Comment by lime-j** [comment]
First of all, thanks for your attention! You can simply change "torch.load(smoother_path)" into "torch.load(smoother_path, strict=False)". up1 is only used as regularization during training, and thus has nothing to do with inference pass.

**Comment by lime-j** [comment]
I will fix and test the code later, but the workaround above can just do the trick.
